/**
 * Centralized Spanish UI strings.
 *
 * All user-facing text lives here (per project convention: code in English,
 * UI in Spanish). Import from this module instead of hardcoding strings inline.
 */
export const strings = {
  appName: "ReciclApp",
  landing: {
    tagline: "Gestión de recogida y reciclaje para la República Dominicana",
    description:
      "Administra puntos de recogida, registra las pasadas semanales y visualiza el impacto del reciclaje.",
    signInWithGoogle: "Iniciar sesión con Google",
  },
  home: {
    title: "Inicio",
    welcome: "Bienvenido",
    role: "Rol",
    signOut: "Cerrar sesión",
    loading: "Cargando...",
    error: "No se pudo cargar tu información.",
    quickLinks: "Accesos rápidos",
    routePass: "Recogida en vivo",
    routePassDesc: "Iniciar una pasada de recogida guiada por el mapa",
    dashboard: "Estadísticas",
    dashboardDesc: "Ver estadísticas y métricas",
    listDesc: "Buscar y editar puntos de recogida",
    mapDesc: "Ver todos los puntos en el mapa",
    greeting: "¡Hola, {name}!",
    rolePill: "Rol: {role}",
    weekProgress: "puntos registrados esta semana",
  },
  roles: {
    read: "Lectura",
    write: "Escritura",
    admin: "Administrador",
  },
  nav: {
    home: "Inicio",
    newPdr: "Nuevo PDR",
    list: "Listado",
    map: "Mapa",
    collectionPass: "Recogida semanal",
    weights: "Registro de peso",
    dashboard: "Estadísticas",
    admin: "Configuración",
    signOut: "Cerrar sesión",
    menu: "Menú",
  },
  common: {
    loading: "Cargando...",
    noAccess: "No tienes permiso para ver esta página.",
    save: "Guardar",
    saving: "Guardando...",
    required: "Este campo es obligatorio",
    cancel: "Cancelar",
    add: "Añadir",
    edit: "Editar",
    delete: "Eliminar",
    confirmDelete: "¿Seguro que quieres eliminar esto?",
    genericError: "Ocurrió un error. Inténtalo de nuevo.",
  },
  admin: {
    title: "Configuración",
    tabUsers: "Usuarios",
    tabTowns: "Configuración de localidad",
    users: {
      addUser: "Añadir usuario",
      editUser: "Editar usuario",
      email: "Correo electrónico",
      name: "Nombre",
      role: "Rol",
      actions: "Acciones",
      loginHint:
        "El usuario tendrá acceso la primera vez que inicie sesión con Google con este correo.",
      deleteConfirm: "¿Eliminar el acceso de este usuario?",
      empty: "No hay usuarios.",
      loadError: "No se pudieron cargar los usuarios.",
    },
    towns: {
      selectTown: "Localidad",
      addTown: "Añadir localidad",
      editTown: "Editar localidad",
      name: "Nombre",
      centerLat: "Latitud del centro",
      centerLng: "Longitud del centro",
      categories: "Categorías",
      categoriesHint: "Pulsa Enter para añadir una categoría.",
      communities: "Comunidades",
      addCommunity: "Añadir comunidad",
      neighborhoods: "Barrios",
      addNeighborhood: "Añadir barrio",
      newCommunity: "Nueva comunidad",
      newNeighborhood: "Nuevo barrio",
      saved: "Cambios guardados.",
      deleteTownConfirm: "¿Eliminar la localidad y toda su configuración?",
      deleteCommunityConfirm: "¿Eliminar la comunidad y sus barrios?",
      deleteNeighborhoodConfirm: "¿Eliminar el barrio?",
      empty: "No hay localidades. Crea una para empezar.",
      loadError: "No se pudo cargar la configuración.",
    },
  },
  list: {
    title: "Puntos de recogida",
    search: "Buscar",
    searchPlaceholder: "Buscar por nombre o referencia…",
    colInternalId: "ID",
    colName: "Nombre",
    colCategory: "Categoría",
    colCommunity: "Comunidad",
    colNeighborhood: "Barrio",
    colDescription: "Descripción",
    colHistory: "Últimas 5 sem.",
    colCreatedAt: "Fecha de alta",
    colLastCollection: "Última recogida",
    colStatus: "Estado",
    deleteConfirm: "¿Eliminar este punto de recogida?",
    empty: "Aún no hay puntos de recogida.",
    emptyFiltered: "No se encontraron puntos con esos filtros.",
    loadError: "No se pudieron cargar los puntos de recogida.",
    count: "puntos",
    communities: "comunidades",
    allBarrios: "Todas",
    allCategories: "Todas",
    showing: "Mostrando",
    of: "de",
    noHistory: "Sin registrar",
    statusAlert: "Alerta",
    filterAlertOnly: "Solo alerta",
  },
  mapPage: {
    title: "Mapa de puntos",
    filterNeighborhood: "Barrio",
    filterCategory: "Categoría",
    all: "Todos",
    loadError: "No se pudo cargar el mapa.",
  },
  collectionPass: {
    title: "Recogida semanal",
    week: "Semana",
    of: "de",
    statusLabel: "Estado",
    save: "Guardar pasada",
    saving: "Guardando...",
    success: "Pasada guardada correctamente.",
    error: "No se pudo guardar la pasada.",
    loadError: "No se pudo cargar la pasada.",
    empty: "No hay puntos de recogida para registrar.",
    notSet: "Sin registrar",
    filterCommunity: "Comunidad",
    filterNeighborhood: "Barrio",
    all: "Todos",
    selectNeighborhoodHint:
      "Selecciona un barrio para ver los puntos de recogida.",
    today: "Semana actual",
    statuses: {
      collected: "Recogido",
      empty: "Vacío",
      unavailable: "No disponible",
      closed: "Cerrado",
    },
  },
  newPdr: {
    title: "Nuevo punto de recogida",
    name: "Nombre",
    description: "Descripción",
    community: "Comunidad",
    neighborhood: "Barrio",
    category: "Categoría",
    location: "Ubicación",
    locationHint: "Toca el mapa para marcar la ubicación del punto.",
    selectedCoords: "Coordenadas seleccionadas",
    noLocation: "Aún no has marcado una ubicación en el mapa.",
    create: "Crear PDR",
    creating: "Creando...",
    success: "Punto de recogida creado correctamente.",
    error: "No se pudo crear el punto de recogida.",
    loadError: "No se pudieron cargar las opciones del formulario.",
    mapKeyMissing: "Falta la clave de Google Maps.",
  },
  dashboard: {
    title: "Estadísticas",
    loadError: "No se pudieron cargar las estadísticas.",
    totalPdrs: "Total PDRs",
    totalCollected: "Recogidas totales",
    totalWeeks: "Semanas registradas",
    collectionRate: "Tasa de recogida",
    communities: "Comunidades",
    collectionsOverTime: "Recogidas por semana",
    weekLabel: "Semana",
    pdrsByCommunity: "PDRs por comunidad",
    pdrsByNeighborhood: "PDRs por barrio",
    pdrsByCategory: "PDRs por categoría",
    latestWeekStatus: "Estado última semana",
    rangeLabel: "Últimas 8 semanas",
    totalPoints: "puntos",
    filterRange: "Periodo",
    filterNeighborhood: "Barrio",
    filterCategory: "Categoría",
    all: "Todo",
    range3m: "3 meses",
    range6m: "6 meses",
    range1y: "1 año",
  },
  weights: {
    title: "Registro de peso",
    date: "Fecha",
    plasticType: "Tipo de plástico",
    weightLbs: "Peso (libras)",
    submit: "Registrar peso",
    submitting: "Registrando...",
    success: "Peso registrado correctamente.",
    error: "No se pudo registrar el peso.",
    loadError: "No se pudieron cargar los registros.",
    empty: "Aún no hay registros de peso.",
    history: "Historial de pesos",
    plasticTypes: {
      pet: "PET",
      hdpe: "HDPE",
      pp: "PP",
      trash: "Basura",
    },
  },
  collectionRoute: {
    title: "Recogida en vivo",
    start: "Iniciar recogida en vivo",
    nextPoint: "Próximo punto",
    recenter: "Centrar en mi ubicación",
    progress: "registrados",
    collectedCount: "recogidos",
    barrioComplete: "completado",
    nextBarrio: "Siguiente barrio",
    online: "En línea",
    syncing: "Sincronizando…",
    offline: "Sin conexión",
    unsynced: "sin guardar",
    locationDenied: "Activa la ubicación para ver tu posición en el mapa.",
    markCollected: "Recogido",
    markEmpty: "Vacío",
    markUnavailable: "No disp.",
    markClosed: "Cerrado",
    allComplete: "¡Pasada completada!",
    noStops: "No hay puntos en este barrio.",
    loadError: "No se pudo cargar la ruta.",
  },
} as const;
