/**
 * Centralized Spanish UI strings.
 *
 * All user-facing text lives here (per project convention: code in English,
 * UI in Spanish). Import from this module instead of hardcoding strings inline.
 */
export const strings = {
  appName: "ReciclApp",
  landing: {
    tagline: "Gestión de recogida y reciclaje para la República Dominicana",
    description:
      "Administra puntos de recogida, registra las pasadas semanales y visualiza el impacto del reciclaje.",
    signInWithGoogle: "Iniciar sesión con Google",
  },
  home: {
    title: "Inicio",
    welcome: "Bienvenido",
    role: "Rol",
    signOut: "Cerrar sesión",
    loading: "Cargando...",
    error: "No se pudo cargar tu información.",
  },
  roles: {
    read: "Lectura",
    write: "Escritura",
    admin: "Administrador",
  },
  nav: {
    home: "Inicio",
    newPdr: "Nuevo PDR",
    list: "Listado",
    map: "Mapa",
    collectionPass: "Pasada semanal",
    signOut: "Cerrar sesión",
    menu: "Menú",
  },
  common: {
    loading: "Cargando...",
    noAccess: "No tienes permiso para ver esta página.",
    save: "Guardar",
    saving: "Guardando...",
    required: "Este campo es obligatorio",
  },
  list: {
    title: "Puntos de recogida",
    search: "Buscar",
    colInternalId: "ID",
    colName: "Nombre",
    colCategory: "Categoría",
    colCommunity: "Comunidad",
    colNeighborhood: "Barrio",
    colCreatedAt: "Fecha de alta",
    empty: "Aún no hay puntos de recogida.",
    loadError: "No se pudieron cargar los puntos de recogida.",
    count: "puntos",
  },
  mapPage: {
    title: "Mapa de puntos",
    filterNeighborhood: "Barrio",
    filterCategory: "Categoría",
    all: "Todos",
    loadError: "No se pudo cargar el mapa.",
  },
  collectionPass: {
    title: "Pasada semanal",
    week: "Semana",
    of: "de",
    statusLabel: "Estado",
    save: "Guardar pasada",
    saving: "Guardando...",
    success: "Pasada guardada correctamente.",
    error: "No se pudo guardar la pasada.",
    loadError: "No se pudo cargar la pasada.",
    empty: "No hay puntos de recogida para registrar.",
    notSet: "Sin registrar",
    statuses: {
      collected: "Recogido",
      empty: "Vacío",
      unavailable: "No disponible",
      closed: "Cerrado",
    },
  },
  newPdr: {
    title: "Nuevo punto de recogida",
    name: "Nombre",
    description: "Descripción",
    community: "Comunidad",
    neighborhood: "Barrio",
    category: "Categoría",
    location: "Ubicación",
    locationHint: "Toca el mapa para marcar la ubicación del punto.",
    selectedCoords: "Coordenadas seleccionadas",
    noLocation: "Aún no has marcado una ubicación en el mapa.",
    create: "Crear PDR",
    creating: "Creando...",
    success: "Punto de recogida creado correctamente.",
    error: "No se pudo crear el punto de recogida.",
    loadError: "No se pudieron cargar las opciones del formulario.",
    mapKeyMissing: "Falta la clave de Google Maps.",
  },
} as const;
