-- Town configuration + pickup points (PDRs).
-- RLS deny-all on every table — the FastAPI backend is the sole data gateway.

-- Towns: a town with its map center and the list of PDR categories it uses.
create table if not exists public.towns (
    id uuid primary key default gen_random_uuid(),
    name text not null unique,
    map_center_lat double precision not null,
    map_center_lng double precision not null,
    categories text[] not null default '{}'
);

-- Communities within a town.
create table if not exists public.communities (
    id uuid primary key default gen_random_uuid(),
    town_id uuid not null references public.towns (id) on delete cascade,
    name text not null,
    unique (town_id, name)
);

-- Neighborhoods (barrios) within a community.
create table if not exists public.neighborhoods (
    id uuid primary key default gen_random_uuid(),
    community_id uuid not null references public.communities (id) on delete cascade,
    name text not null,
    unique (community_id, name)
);

-- Pickup points. community/neighborhood/category are stored as the selected
-- values (per PRD); the town-config tables above drive the form dropdowns.
create table if not exists public.pdrs (
    id uuid primary key default gen_random_uuid(),
    internal_id bigint generated by default as identity,
    name text not null,
    description text,
    community text not null,
    neighborhood text not null,
    category text not null,
    lat double precision not null,
    lng double precision not null,
    created_at timestamptz not null default now(),
    created_by uuid references public.users (id) on delete set null
);

alter table public.towns enable row level security;
alter table public.communities enable row level security;
alter table public.neighborhoods enable row level security;
alter table public.pdrs enable row level security;
